services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATA: /var/lib/mysql/data
      MYSQL_DB: my_notions_network
    volumes:
      - mysql: /data/mysql
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  mysql:
    driver: local

networks:
  spring-demo:
    driver: bridge
