name: GitHub Actions My Notions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  frontend-pipeline:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build
        if: always()
      - name: linting typescript
        run: npm run lint
        if: always()
      - name: linting scss
        run: npm run stylelint
        if: always()
      - name: run unit tests
        run: npm run test
        if: always()
